name: fluent_ui
description: Implements fluent ui in flutter
version: 0.0.3
author: bdlukaa
homepage: https://github.com/bdlukaa/fluent_ui

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  fluentui_system_icons: ^1.1.89

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: