name: fluent_ui
description: Implements Fluent UI in Flutter. Based on the official documentation
version: 1.7.4
homepage: https://github.com/bdlukaa/fluent_ui

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
