name: fluent_ui
description: Implements Fluent Ui in flutter. Based on the official documentation
version: 0.0.6
homepage: https://github.com/bdlukaa/fluent_ui

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  fl_toast: ^2.0.0
  fluentui_icons: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
